// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrantControlSystem.Models;

namespace MigrantControlSystem.Migrations
{
    [DbContext(typeof(MCSDbContext))]
    [Migration("20200606154932_migracija123")]
    partial class migracija123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MigrantControlSystem.Models.Lokacija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("x")
                        .HasColumnType("float");

                    b.Property<double>("y")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Lokacija");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Migrant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("drzavaPorijekla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("migrantskiCentarid")
                        .HasColumnType("int");

                    b.Property<int?>("policijskaStanicaid")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("migrantskiCentarid");

                    b.HasIndex("policijskaStanicaid");

                    b.ToTable("Migrant");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MigrantskiCentar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kapacitet")
                        .HasColumnType("int");

                    b.Property<int?>("lokacijaid")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lokacijaid");

                    b.ToTable("MigrantskiCentar");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MigrantskiCentar");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.PolicijskaStanica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("lokacijaid")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lokacijaid");

                    b.ToTable("PolicijskaStanica");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Zahtjev", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("migrantid")
                        .HasColumnType("int");

                    b.Property<int?>("migrantskiCentarid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("migrantid");

                    b.HasIndex("migrantskiCentarid");

                    b.ToTable("Zahtjev");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Zahtjev");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MCOtvoreniTip", b =>
                {
                    b.HasBaseType("MigrantControlSystem.Models.MigrantskiCentar");

                    b.Property<int>("brojRegistrovanih")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MCOtvoreniTip");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MCZatvoreniTip", b =>
                {
                    b.HasBaseType("MigrantControlSystem.Models.MigrantskiCentar");

                    b.Property<int>("brojZatvorenih")
                        .HasColumnType("int");

                    b.Property<int>("standardniPeriodZadrzavanjaMigranta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MCZatvoreniTip");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Deportacija", b =>
                {
                    b.HasBaseType("MigrantControlSystem.Models.Zahtjev");

                    b.Property<int>("dodatniRokIzvrsenja")
                        .HasColumnType("int");

                    b.Property<string>("drzava")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Deportacija");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Hapsenje", b =>
                {
                    b.HasBaseType("MigrantControlSystem.Models.Zahtjev");

                    b.Property<int>("dodatniRokIzvrsenja")
                        .HasColumnName("Hapsenje_dodatniRokIzvrsenja")
                        .HasColumnType("int");

                    b.Property<int?>("policijskaStanicaid")
                        .HasColumnType("int");

                    b.HasIndex("policijskaStanicaid");

                    b.HasDiscriminator().HasValue("Hapsenje");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Premjestanje", b =>
                {
                    b.HasBaseType("MigrantControlSystem.Models.Zahtjev");

                    b.Property<int>("dodatniRokIzvrsenja")
                        .HasColumnName("Premjestanje_dodatniRokIzvrsenja")
                        .HasColumnType("int");

                    b.Property<int?>("dolazniMigrantskiCentarid")
                        .HasColumnType("int");

                    b.HasIndex("dolazniMigrantskiCentarid");

                    b.HasDiscriminator().HasValue("Premjestanje");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Migrant", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.MigrantskiCentar", "migrantskiCentar")
                        .WithMany("migranti")
                        .HasForeignKey("migrantskiCentarid");

                    b.HasOne("MigrantControlSystem.Models.PolicijskaStanica", "policijskaStanica")
                        .WithMany()
                        .HasForeignKey("policijskaStanicaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MigrantskiCentar", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Lokacija", "lokacija")
                        .WithMany()
                        .HasForeignKey("lokacijaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.PolicijskaStanica", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Lokacija", "lokacija")
                        .WithMany()
                        .HasForeignKey("lokacijaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Zahtjev", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Migrant", "migrant")
                        .WithMany()
                        .HasForeignKey("migrantid");

                    b.HasOne("MigrantControlSystem.Models.MigrantskiCentar", "migrantskiCentar")
                        .WithMany("zahtjevi")
                        .HasForeignKey("migrantskiCentarid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Hapsenje", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.PolicijskaStanica", "policijskaStanica")
                        .WithMany()
                        .HasForeignKey("policijskaStanicaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Premjestanje", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.MigrantskiCentar", "dolazniMigrantskiCentar")
                        .WithMany()
                        .HasForeignKey("dolazniMigrantskiCentarid");
                });
#pragma warning restore 612, 618
        }
    }
}
