// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrantControlSystem.Models;

namespace MigrantControlSystem.Migrations
{
    [DbContext(typeof(MCSDbContext))]
    partial class MCSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MigrantControlSystem.Models.Lokacija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("x")
                        .HasColumnType("int");

                    b.Property<int>("y")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Lokacija");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Migrant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("drzavaPorijekla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("migrantskiCentarid")
                        .HasColumnType("int");

                    b.Property<int?>("policijskaStanicaid")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("migrantskiCentarid");

                    b.HasIndex("policijskaStanicaid");

                    b.ToTable("Migrant");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MigrantskiCentar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("kapacitet")
                        .HasColumnType("int");

                    b.Property<int?>("lokacijaid")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lokacijaid");

                    b.ToTable("MigrantskiCentar");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.PolicijskaStanica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("lokacijaid")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lokacijaid");

                    b.ToTable("PolicijskaStanica");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Zahtjev", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("migrantid")
                        .HasColumnType("int");

                    b.Property<int?>("migrantskiCentarid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("migrantid");

                    b.HasIndex("migrantskiCentarid");

                    b.ToTable("Zahtjev");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Migrant", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.MigrantskiCentar", "migrantskiCentar")
                        .WithMany("migranti")
                        .HasForeignKey("migrantskiCentarid");

                    b.HasOne("MigrantControlSystem.Models.PolicijskaStanica", "policijskaStanica")
                        .WithMany()
                        .HasForeignKey("policijskaStanicaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.MigrantskiCentar", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Lokacija", "lokacija")
                        .WithMany()
                        .HasForeignKey("lokacijaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.PolicijskaStanica", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Lokacija", "lokacija")
                        .WithMany()
                        .HasForeignKey("lokacijaid");
                });

            modelBuilder.Entity("MigrantControlSystem.Models.Zahtjev", b =>
                {
                    b.HasOne("MigrantControlSystem.Models.Migrant", "migrant")
                        .WithMany()
                        .HasForeignKey("migrantid");

                    b.HasOne("MigrantControlSystem.Models.MigrantskiCentar", "migrantskiCentar")
                        .WithMany("zahtjevi")
                        .HasForeignKey("migrantskiCentarid");
                });
#pragma warning restore 612, 618
        }
    }
}
